#ifndef _CHTTP_DEFINES_H_
#define _CHTTP_DEFINES_H_

#define CHTTP_HEADER_KEY_LENGTH       64
#define CHTTP_HEADER_VALUE_LENGTH   4096
#define CHTTP_URI_LENGTH             256
#define CHTTP_HTTP_VERSION_LENGTH     64
#define CHTTP_REASON_PHRASE_LENGTH    64
#define CHTTP_BODY_LENGTH          16384

#endif
